recovery_behaviors:
  # - name: 'in_place_blanking'
  #   type: blanking_recovery/BlankingRecovery
  # - name: 'refresh_vo'
  #   type: 'clear_costmap_recovery/ClearCostmapRecovery'
   - name: 'costmap_reset_far'
     type: 'clear_costmap_recovery/ClearCostmapRecovery'
  # - name: 'visited_recovery'
  #   type: visited_recovery/VisitedRecovery
  # - name: 'small_rotation_blanking_1'
  #   type: blanking_recovery/BlankingRecovery
  # - name: 'small_rotation_blanking_2'
  #   type: blanking_recovery/BlankingRecovery
  # - name: 'small_rotation_blanking_3'
  #   type: blanking_recovery/BlankingRecovery
   - name: 'dummy'
     type: 'clear_costmap_recovery/ClearCostmapRecovery'

in_place_blanking:
  max_rotational_vel: 0.4
  rotation_steps: 0
  clearing_max_dist: 0.7
  count_threshold: 450
  use_roof_camera: false

small_rotation_blanking_1:
  max_rotational_vel: 0.4
  rotation_steps: 2
  clearing_max_dist: 0.7
  count_threshold: 450
  use_roof_camera: false
  max_rotation_angle: !degrees 120
  min_rotation_angle: !degrees 0

small_rotation_blanking_2:
  max_rotational_vel: 0.4
  rotation_steps: 2
  clearing_max_dist: 0.7
  count_threshold: 450
  use_roof_camera: false
  max_rotation_angle: !degrees 120
  min_rotation_angle: !degrees 0

small_rotation_blanking_3:
  max_rotational_vel: 0.4
  rotation_steps: 2
  clearing_max_dist: 0.7
  count_threshold: 450
  use_roof_camera: false
  max_rotation_angle: !degrees 120
  min_rotation_angle: !degrees 0

small_rotation_blanking:
  max_rotational_vel: 0.4
  rotation_steps: 3
  clearing_max_dist: 0.7
  count_threshold: 450
  use_roof_camera: false
  max_rotation_angle: !degrees 45
  min_rotation_angle: !degrees -45

single_clockwise_rotation_blanking:
  max_rotational_vel: 0.4
  rotation_steps: 1
  clearing_max_dist: 0.7
  count_threshold: 450
  use_roof_camera: false
  max_rotation_angle: !degrees 45
  min_rotation_angle: !degrees 0

single_counterclockwise_rotation_blanking:
  max_rotational_vel: 0.4
  rotation_steps: 1
  clearing_max_dist: 0.7
  count_threshold: 450
  use_roof_camera: false
  max_rotation_angle: !degrees 0
  min_rotation_angle: !degrees -90

full_rotation_blanking:
  max_rotational_vel: 0.4
  rotation_steps: 6
  clearing_max_dist: 0.7
  count_threshold: 450
  use_roof_camera: false

visited_recovery:
  footprint_radius: 0.25
  min_pose_distance: 0.1
  layer_names: ["obstacle_laser_layer", "obstacle_rgbd_layer", "obstacle_vo_layer"]

costmap_reset_far:
  reset_distance: 5.5
  layer_names: ["obstacle_laser_layer", "obstacle_rgbd_layer", "obstacle_vo_layer"]

costmap_reset_close:
  reset_distance: 1.5
  layer_names: ["obstacle_laser_layer", "obstacle_rgbd_layer", "obstacle_vo_layer"]

dummy:
  reset_distance: 5.5
  layer_names: ["obstacle_laser_layer", "obstacle_rgbd_layer", "obstacle_vo_layer"]

refresh_vo:
  reset_distance: 0.0
  layer_names: ["obstacle_vo_layer"]
